apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-controller-role
  namespace: island-ci-cd-poc
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
