apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-tekton-rolebinding
  namespace: island-ci-cd-poc
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-tekton-role
  apiGroup: rbac.authorization.k8s.io
