apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    chains.tekton.dev/signed: "true"
  labels:
    app.kubernetes.io/instance: sample-rest-api
    app.kubernetes.io/name: sample-rest-api
    operator.tekton.dev/operand-name: openshift-pipelines-addons
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: kubernetes
    tekton.dev/pipeline: sample-rest-api
  name: sample-rest-api-run
  namespace: island-ci-cd-poc
spec:
  params:
  - name: APP_NAME
    value: sample-rest-api
  - name: GIT_REPO
    value: https://github.com/redhat-na-ssa/island-health-poc.git
  - name: GIT_REVISION
    value: ""
  - name: IMAGE_NAME
    value: image-registry.openshift-image-registry.svc:5000/island-ci-cd-poc/sample-rest-api
  - name: PATH_CONTEXT
    value: .
  pipelineRef:
    name: sample-rest-api
  taskRunTemplate:
    serviceAccountName: pipeline
  timeouts:
    pipeline: 1h0m0s
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
          labels:
            tekton.dev/pipeline: island-health-poc
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
