apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-controller-role
  namespace: island-ci-cd-poc
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  - apiGroups: ["route.openshift.io"]
    resources: ["routes"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-app-controller-rolebinding
  namespace: island-ci-cd-poc
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-app-controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-tekton-role
  namespace: island-ci-cd-poc
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines"]
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-tekton-rolebinding
  namespace: island-ci-cd-poc
subjects:
  - kind: ServiceAccount
    name: openshift-gitops-argocd-application-controller
    namespace: openshift-gitops
roleRef:
  kind: Role
  name: argocd-tekton-role
  apiGroup: rbac.authorization.k8s.io
