userData: |-
  #cloud-config
  user: user1
  password: openshift
  chpasswd: { expire: False }
  packages:
    - git
  runcmd:
    - export SERVICE_LOCAL=fedora02
    - git clone https://github.com/bugbiteme/python-rest-api.git /home/user1/app
    - cd /home/user1/app
    - sh /home/user1/app/start-on-vm.sh


