apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    app: fedora02
    vm.kubevirt.io/template: fedora-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: "1"
    vm.kubevirt.io/template.version: v0.26.0
  name: fedora02
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      creationTimestamp: null
      name: fedora02
    spec:
      sourceRef:
        kind: DataSource
        name: fedora
        namespace: openshift-virtualization-os-images
      storage:
        resources:
          requests:
            storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        app: service-b
        kubevirt.io/domain: fedora02
        kubevirt.io/size: small
        version: VM2
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - macAddress: 02:1f:49:00:00:07
            masquerade: {}
            model: virtio
            name: default
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 2Gi
        resources: {}
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - dataVolume:
          name: fedora02
        name: rootdisk
      - cloudInitConfigDrive:
          userData: |-
            #cloud-config
            user: user1
            password: openshift
            chpasswd: { expire: False }
            packages:
              - git
            runcmd:
              - export SERVICE_LOCAL=fedora02
              - git clone https://github.com/bugbiteme/python-rest-api.git /home/user1/app
              - cd /home/user1/app
              - sh /home/user1/app/start-on-vm.sh
        name: cloudinitdisk