apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-vs
spec:
  hosts:
  - "*"
  gateways:
  - hello-gateway
  http:
  - route:
    - destination:
        host: service-a
#        port:
#          name: http-8080
#          number: 8080
#---
#apiVersion: networking.istio.io/v1beta1
#kind: VirtualService
##metadata:
#  name: service-b
#spec:
#  hosts:
#    - service-b
#  http:
#  - route:
#    - destination:
#        host: service-b
#        subset: v1
#      weight: 100
#    - destination:
#        host: service-b
#        subset: v2
#      weight: 0
#    - destination:
#        host: service-b
##        subset: VM1
#     weight: 0
#    - destination:
#        host: service-b
#        subset: VM2
#      weight: 0